dbLoadDatabase("C:\SlowControls\EPICS\Utilities\Bin\tCat.dbd",0,0)
tCat_registerRecordDeviceDriver(pdbbase)
callbackSetQueueSize(50000)
tcSetScanRate(10, 5)

tcSetAlias("X1PLC1", "IFO=H1,END=X")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC1\H1ECATX1_PLC1.opc.txt","-l -rn -yi -cp")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC1\H1ECATX1_PLC1.chn.txt","-l")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC1\H1ECATX1_PLC1.req","-lb")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC1\H1ECATX1_PLC1.ini","-l -ns")
tcGenerateMacros("C:\SlowControls\Target\H1ECATX1\PLC1\..\ADL")
tcLoadRecords ("C:\SlowControls\Target\H1ECATX1\PLC1\PLC1.tpy")

tcSetAlias("X1PLC2", "IFO=H1,END=X")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC2\H1ECATX1_PLC2.opc.txt","-l -rn -yi -cp")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC2\H1ECATX1_PLC2.chn.txt","-l")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC2\H1ECATX1_PLC2.req","-lb")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC2\H1ECATX1_PLC2.ini","-l -ns")
tcGenerateMacros("C:\SlowControls\Target\H1ECATX1\PLC2\..\ADL")
tcLoadRecords ("C:\SlowControls\Target\H1ECATX1\PLC2\PLC2.tpy")

tcSetAlias("X1PLC3", "IFO=H1,END=X")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC3\H1ECATX1_PLC3.opc.txt","-l -rn -yi -cp")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC3\H1ECATX1_PLC3.chn.txt","-l")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC3\H1ECATX1_PLC3.req","-lb")
tcGenerateList("C:\SlowControls\Target\H1ECATX1\PLC3\H1ECATX1_PLC3.ini","-l -ns")
tcGenerateMacros("C:\SlowControls\Target\H1ECATX1\PLC3\..\ADL")
tcLoadRecords ("C:\SlowControls\Target\H1ECATX1\PLC3\PLC3.tpy")

iocInit()
